services:
  railwayapp:
    image: railwayapp
    build:
      context: .
      dockerfile: src/API/RailwayApp.Api/Dockerfile
    depends_on:
      - railwayappDb
      - railwayappRabbitmq

  railwayappDb:
    image: mariadb:10.7
    restart: always
    environment:
      MARIADB_DATABASE: RailwayDb
      MARIADB_USER: root
      MARIADB_PASSWORD: root
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./.containers/mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  railwayappRabbitmq:
    image: rabbitmq:management
    hostname: railwayapp-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"